### ISSUE TITLE
manual annotations

### ISSUE THREAD

**Issue by bwittmann** [psweens/VAN-GAN#5]
Dear psweens,

First of all, I want to thank you for your significant contribution to the vessel segmentation community.
One question: Are you willing to share your manual annotations with the community?
I would highly appreciate this and obviously also reference your work adequately.

Thanks in advance for your time and effort. 

Best,
Bastian

**Comment by psweens** [comment]
Hi Bastian,
Thanks for your interest.
Which manual annotations are you referring to?
Cheers,
Paul

**Comment by bwittmann** [comment]
Dear Paul,

Sorry for being so vague. 
Specifically, I am referring to the experimental photoacoustic datasets (Table 6 in supplement).
Would be highly appreciated!

Best,
Bastian

**Comment by psweens** [comment]
Hi Bastian,
No problem. You'll need to email Sarah Bohndiek (emails are here https://www.bohndieklab.org) to request the photoacoustic datasets as sadly they're not mine, and the biological study for the PDX tumours models has yet to be published. Feel free to cc me in the email.

The simulated photoacoustic images as well as the synthetic vascular labels will be released when the VAN-GAN manuscript is published - I hoping this will be in the next month or two.

Cheers,
Paul
