### ISSUE TITLE
Data arrangement 

### ISSUE THREAD

**Issue by ZahraMESBAHI** [psweens/VAN-GAN#6]
I would like to know the data type and the data file how should be arrange.

**Comment by psweens** [comment]
Hi,
Thanks for taking an interest in the repo. The folder format is:
```
root/
├── raw_data/
├── filtered/
│   ├── trainA/
│   └── testA/
│   └── valA/
│   └── trainB/
│   └── testB/
│   └── valB/
├── trainA/
├── testA/
├── valA/
├── trainB/
├── testB/
└── valB/
```
All images should ideally be stored as float32.

An example of the folder format as well as example datasets will be release when the manuscript is publish.

Cheers,

Paul

**Comment by ZahraMESBAHI** [comment]
Thank you so much for your fast reply. 
I have further questions
have trainA and trainB  included 2 volumeric samples ? and has the volumetric sample stored as slices? and what extension ends the slice images ?

thank you very much to answer my questions, because I am so confused.

**Comment by psweens** [comment]
For both A and B volumetric images are used not slices. Their raw files _(.tiff)_ are contained in subfolders in _raw_data_
